/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import javax.swing.JButton;

/**
 *
 * @author M.Hidayatullah
 */
public class MainMenuView extends javax.swing.JFrame {
    
    MainMenuController control;
    /**
     * Creates new form MainMenuView
     */
    public MainMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempat_wisata = new javax.swing.JPanel();
        btn_tmbh_wisata = new javax.swing.JButton();
        btn_ubh_wisata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JPanel();
        btn_tmbh_pel = new javax.swing.JButton();
        btn_ubh_pel = new javax.swing.JButton();
        kendaraan = new javax.swing.JPanel();
        btn_tmbh_kend = new javax.swing.JButton();
        btn_ubh_kend = new javax.swing.JButton();
        pemesanan = new javax.swing.JPanel();
        btn_tmbh_pems = new javax.swing.JButton();
        btn_ubh_pems = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempat_wisata.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempat Wisata"));

        btn_tmbh_wisata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tmbh_wisata.setText("Tambah");
        btn_tmbh_wisata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_ubh_wisata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ubh_wisata.setText("Lihat");
        btn_ubh_wisata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout tempat_wisataLayout = new javax.swing.GroupLayout(tempat_wisata);
        tempat_wisata.setLayout(tempat_wisataLayout);
        tempat_wisataLayout.setHorizontalGroup(
            tempat_wisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempat_wisataLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn_tmbh_wisata, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ubh_wisata, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        tempat_wisataLayout.setVerticalGroup(
            tempat_wisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempat_wisataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tempat_wisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tmbh_wisata, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btn_ubh_wisata, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Main Menu");

        pelanggan.setBorder(javax.swing.BorderFactory.createTitledBorder("Pelanggan"));

        btn_tmbh_pel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tmbh_pel.setText("Tambah");
        btn_tmbh_pel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_ubh_pel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ubh_pel.setText("Lihat");
        btn_ubh_pel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pelangganLayout = new javax.swing.GroupLayout(pelanggan);
        pelanggan.setLayout(pelangganLayout);
        pelangganLayout.setHorizontalGroup(
            pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_tmbh_pel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ubh_pel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        pelangganLayout.setVerticalGroup(
            pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tmbh_pel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btn_ubh_pel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        kendaraan.setBorder(javax.swing.BorderFactory.createTitledBorder("Kendaraan"));

        btn_tmbh_kend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tmbh_kend.setText("Tambah");
        btn_tmbh_kend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_ubh_kend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ubh_kend.setText("Lihat");
        btn_ubh_kend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout kendaraanLayout = new javax.swing.GroupLayout(kendaraan);
        kendaraan.setLayout(kendaraanLayout);
        kendaraanLayout.setHorizontalGroup(
            kendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_tmbh_kend, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btn_ubh_kend, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        kendaraanLayout.setVerticalGroup(
            kendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tmbh_kend, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btn_ubh_kend, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        pemesanan.setBorder(javax.swing.BorderFactory.createTitledBorder("Pemesanan"));

        btn_tmbh_pems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tmbh_pems.setText("Tambah");
        btn_tmbh_pems.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_ubh_pems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ubh_pems.setText("Lihat");
        btn_ubh_pems.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pemesananLayout = new javax.swing.GroupLayout(pemesanan);
        pemesanan.setLayout(pemesananLayout);
        pemesananLayout.setHorizontalGroup(
            pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_tmbh_pems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88)
                .addComponent(btn_ubh_pems, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        pemesananLayout.setVerticalGroup(
            pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tmbh_pems, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btn_ubh_pems, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pemesanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kendaraan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelanggan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempat_wisata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempat_wisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tmbh_kend;
    private javax.swing.JButton btn_tmbh_pel;
    private javax.swing.JButton btn_tmbh_pems;
    private javax.swing.JButton btn_tmbh_wisata;
    private javax.swing.JButton btn_ubh_kend;
    private javax.swing.JButton btn_ubh_pel;
    private javax.swing.JButton btn_ubh_pems;
    private javax.swing.JButton btn_ubh_wisata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel kendaraan;
    private javax.swing.JPanel pelanggan;
    private javax.swing.JPanel pemesanan;
    private javax.swing.JPanel tempat_wisata;
    // End of variables declaration//GEN-END:variables
    public void setController(MainMenuController c){
        this.control = c;
        btn_tmbh_wisata.addActionListener(c);
        btn_ubh_wisata.addActionListener(c);
        
        btn_tmbh_kend.addActionListener(c);
        btn_ubh_kend.addActionListener(c);
        
        btn_tmbh_pel.addActionListener(c);
        btn_ubh_pel.addActionListener(c);
        
        btn_tmbh_pems.addActionListener(c);
        btn_ubh_pems.addActionListener(c);
    }

    public JButton getBtn_tmbh_kend() {
        return btn_tmbh_kend;
    }

    public JButton getBtn_tmbh_pel() {
        return btn_tmbh_pel;
    }

    public JButton getBtn_tmbh_pems() {
        return btn_tmbh_pems;
    }

    public JButton getBtn_tmbh_wisata() {
        return btn_tmbh_wisata;
    }

    public JButton getBtn_ubh_pems() {
        return btn_ubh_pems;
    }

    public JButton getBtn_ubh_pel() {
        return btn_ubh_pel;
    }

    public JButton getBtn_ubh_wisata() {
        return btn_ubh_wisata;
    }

    public JButton getBtn_ubh_kend() {
        return btn_ubh_kend;
    }
    
    
}
